name: sqlproj-sample

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build SQL Project
      run: msbuild "./Staff/Staff.sqlproj"

      - name: Deploy
  uses: azure/sql-action@v2
  with:
    connection-string: ${{ Data Source=AREF;Initial Catalog=Member;Integrated Security=True;Connect Timeout=60;Encrypt=True;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False}}
    action: 'publish'
    path: 'bin/Staff/Staff.dacpac'


